# Generated by Django 5.2.6 on 2025-09-30 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRoles',
            fields=[
                ('systemRoleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('systemRole', models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('CLIENT', 'client')], max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
