# Generated by Django 5.2.6 on 2025-10-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_kycverified'),
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCLogs',
            fields=[
                ('logID', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('Rejected', 'Rejected')], help_text='Whether the KYC was approved or rejected', max_length=10)),
                ('reviewedAt', models.DateTimeField(help_text='When the review decision was made')),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for rejection or additional notes')),
                ('userEmail', models.EmailField(max_length=64)),
                ('userAccountID', models.BigIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('accountFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_logs', to=settings.AUTH_USER_MODEL)),
                ('kycID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.kyc')),
                ('reviewedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Log',
                'verbose_name_plural': 'KYC Logs',
                'ordering': ['-reviewedAt'],
                'indexes': [models.Index(fields=['-reviewedAt'], name='adminpanel__reviewe_a8552e_idx'), models.Index(fields=['action'], name='adminpanel__action_ffbe16_idx'), models.Index(fields=['accountFK'], name='adminpanel__account_0675e3_idx')],
            },
        ),
    ]
