# Generated by Django 5.2.6 on 2025-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_kyclogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyclogs',
            name='kycID',
            field=models.BigIntegerField(help_text='KYC record ID (original record deleted after review)'),
        ),
    ]
