# Generated by Django 5.2.6 on 2025-10-06 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_kyclogs_kycid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyclogs',
            old_name='logID',
            new_name='kycLogID',
        ),
        migrations.AlterField(
            model_name='kyclogs',
            name='accountFK',
            field=models.ForeignKey(help_text='The user account whose KYC was reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kyclogs',
            name='kycID',
            field=models.BigIntegerField(help_text='Original KYC record ID (record deleted after review for privacy)'),
        ),
    ]
