# Generated by Django 5.2.8 on 2025-12-09
# Admin Panel - Certification Verification Logs

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_workercertification_specializationid'),
        ('adminpanel', '0003_kyclogs_kyctype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationLog',
            fields=[
                ('certLogID', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificationID', models.BigIntegerField(help_text='ID of the WorkerCertification that was reviewed')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='APPROVED or REJECTED', max_length=20)),
                ('reviewedAt', models.DateTimeField(help_text='Timestamp of verification action')),
                ('reason', models.TextField(blank=True, default='', help_text='Notes for approval or reason for rejection')),
                ('workerEmail', models.EmailField(help_text='Email of the worker at time of verification', max_length=254)),
                ('workerAccountID', models.BigIntegerField(help_text='Account ID of the worker')),
                ('certificationName', models.CharField(help_text='Name of the certification at time of verification', max_length=255)),
                ('reviewedBy', models.ForeignKey(blank=True, help_text='Admin who performed the verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('workerID', models.ForeignKey(help_text='Worker profile this certification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='certification_logs', to='accounts.workerprofile')),
            ],
            options={
                'db_table': 'certification_logs',
                'ordering': ['-reviewedAt'],
            },
        ),
        migrations.AddIndex(
            model_name='certificationlog',
            index=models.Index(fields=['certificationID', 'reviewedAt'], name='certificati_certifi_idx'),
        ),
        migrations.AddIndex(
            model_name='certificationlog',
            index=models.Index(fields=['workerID', 'reviewedAt'], name='certificati_workerI_idx'),
        ),
        migrations.AddIndex(
            model_name='certificationlog',
            index=models.Index(fields=['action'], name='certificati_action_idx'),
        ),
    ]
