# Generated by Django 5.2.6 on 2025-10-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_rename_logid_kyclogs_kyclogid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyclogs',
            name='kycType',
            field=models.CharField(choices=[('USER', 'User'), ('AGENCY', 'Agency')], default='USER', help_text='Indicates whether the KYC was for a user account or an agency', max_length=10),
        ),
    ]
