# Generated by Django 5.2.8 on 2025-11-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_kyclogs_kyctype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faqID', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('account', 'Account & Profile'), ('jobs', 'Jobs & Hiring'), ('payments', 'Payments & Billing'), ('workers', 'For Workers'), ('clients', 'For Clients'), ('agencies', 'For Agencies'), ('safety', 'Safety & Security'), ('general', 'General')], default='general', max_length=20)),
                ('sortOrder', models.IntegerField(default=0)),
                ('viewCount', models.IntegerField(default=0)),
                ('isPublished', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'sortOrder'],
            },
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('responseID', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short title for the response', max_length=100)),
                ('content', models.TextField(help_text='The full response text')),
                ('category', models.CharField(choices=[('account', 'Account Issues'), ('payment', 'Payment Issues'), ('technical', 'Technical Problems'), ('general', 'General')], default='general', max_length=20)),
                ('shortcuts', models.JSONField(blank=True, default=list, help_text='List of shortcut keywords')),
                ('usageCount', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canned_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canned Response',
                'verbose_name_plural': 'Canned Responses',
                'ordering': ['-usageCount', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticketID', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Brief description of the issue', max_length=200)),
                ('category', models.CharField(choices=[('account', 'Account Issues'), ('payment', 'Payment Issues'), ('technical', 'Technical Problems'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('general', 'General Inquiry')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_user', 'Waiting for User'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('lastReplyAt', models.DateTimeField(blank=True, null=True)),
                ('resolvedAt', models.DateTimeField(blank=True, null=True)),
                ('assignedTo', models.ForeignKey(blank=True, help_text='Admin handling this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('userFK', models.ForeignKey(help_text='User who submitted the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketReply',
            fields=[
                ('replyID', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Reply message content')),
                ('isSystemMessage', models.BooleanField(default=False)),
                ('attachmentURL', models.URLField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('senderFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replies', to=settings.AUTH_USER_MODEL)),
                ('ticketFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='adminpanel.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Reply',
                'verbose_name_plural': 'Ticket Replies',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('reportID', models.BigAutoField(primary_key=True, serialize=False)),
                ('reportType', models.CharField(choices=[('user', 'User Report'), ('job', 'Job Posting'), ('review', 'Review'), ('message', 'Message'), ('other', 'Other')], default='user', max_length=10)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('fraud', 'Fraud/Scam'), ('inappropriate', 'Inappropriate Content'), ('fake_profile', 'Fake Profile'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('relatedContentID', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('adminNotes', models.TextField(blank=True, default='')),
                ('actionTaken', models.CharField(choices=[('none', 'No Action'), ('warning', 'Warning Issued'), ('suspended', 'Account Suspended'), ('banned', 'Account Banned'), ('content_removed', 'Content Removed')], default='none', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('resolvedAt', models.DateTimeField(blank=True, null=True)),
                ('reportedUserFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['-createdAt'], name='adminpanel__created_8a9f85_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='adminpanel__status_bb623a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='adminpanel__priorit_cb784b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='adminpanel__categor_11a477_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assignedTo'], name='adminpanel__assigne_460e54_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['-createdAt'], name='adminpanel__created_301685_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status'], name='adminpanel__status_694d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reportType'], name='adminpanel__reportT_47a4b1_idx'),
        ),
    ]
