# Generated by Django 5.2.8 on 2025-11-30 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_support_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('settingsID', models.BigAutoField(primary_key=True, serialize=False)),
                ('platformFeePercentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Platform fee percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('escrowHoldingDays', models.IntegerField(default=7, help_text='Days to hold funds in escrow before release')),
                ('maxJobBudget', models.DecimalField(decimal_places=2, default=100000.0, help_text='Maximum allowed job budget', max_digits=12)),
                ('minJobBudget', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum allowed job budget', max_digits=12)),
                ('workerVerificationRequired', models.BooleanField(default=True, help_text='Require KYC verification for workers')),
                ('autoApproveKYC', models.BooleanField(default=False, help_text='Automatically approve KYC submissions')),
                ('kycDocumentExpiryDays', models.IntegerField(default=365, help_text='Days until KYC documents expire')),
                ('maintenanceMode', models.BooleanField(default=False, help_text='Enable maintenance mode (blocks user access)')),
                ('sessionTimeoutMinutes', models.IntegerField(default=60, help_text='Session timeout in minutes')),
                ('maxUploadSizeMB', models.IntegerField(default=10, help_text='Maximum file upload size in MB')),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.ForeignKey(blank=True, help_text='Admin who last updated settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('adminID', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='moderator', max_length=15)),
                ('permissions', models.JSONField(default=list, help_text='List of permission strings')),
                ('isActive', models.BooleanField(default=True, help_text='Whether this admin account is active')),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accountFK', models.OneToOneField(help_text='Linked user account', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Account',
                'verbose_name_plural': 'Admin Accounts',
                'indexes': [models.Index(fields=['role'], name='adminpanel__role_aca1c5_idx'), models.Index(fields=['isActive'], name='adminpanel__isActiv_aca720_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('auditLogID', models.BigAutoField(primary_key=True, serialize=False)),
                ('adminEmail', models.EmailField(help_text='Snapshot of admin email (in case account is deleted)', max_length=64)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('kyc_approval', 'KYC Approval'), ('kyc_rejection', 'KYC Rejection'), ('payment_release', 'Payment Release'), ('payment_refund', 'Payment Refund'), ('user_ban', 'User Ban'), ('user_unban', 'User Unban'), ('user_suspend', 'User Suspend'), ('settings_change', 'Settings Change'), ('admin_create', 'Admin Create'), ('admin_update', 'Admin Update'), ('admin_delete', 'Admin Delete'), ('job_update', 'Job Update'), ('job_cancel', 'Job Cancel'), ('ticket_reply', 'Ticket Reply'), ('ticket_close', 'Ticket Close'), ('report_review', 'Report Review'), ('faq_create', 'FAQ Create'), ('faq_update', 'FAQ Update'), ('faq_delete', 'FAQ Delete')], help_text='Type of action performed', max_length=30)),
                ('entityType', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('job', 'Job'), ('kyc', 'KYC'), ('payment', 'Payment'), ('ticket', 'Support Ticket'), ('report', 'Report'), ('settings', 'Settings'), ('faq', 'FAQ'), ('category', 'Category')], help_text='Type of entity affected', max_length=20)),
                ('entityID', models.CharField(blank=True, default='', help_text='ID of the affected entity', max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('beforeValue', models.JSONField(blank=True, help_text='State before the change', null=True)),
                ('afterValue', models.JSONField(blank=True, help_text='State after the change', null=True)),
                ('ipAddress', models.GenericIPAddressField(blank=True, help_text='IP address of the admin', null=True)),
                ('userAgent', models.TextField(blank=True, default='', help_text='Browser/client user agent')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('adminFK', models.ForeignKey(help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['-createdAt'], name='adminpanel__created_3c5926_idx'), models.Index(fields=['action'], name='adminpanel__action_fac12d_idx'), models.Index(fields=['adminFK'], name='adminpanel__adminFK_d93624_idx'), models.Index(fields=['entityType'], name='adminpanel__entityT_aea4a2_idx'), models.Index(fields=['entityType', 'entityID'], name='adminpanel__entityT_72b6c5_idx')],
            },
        ),
    ]
