# Generated by Django 6.0 on 2025-12-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_audit_settings_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('kyc_approval', 'KYC Approval'), ('kyc_rejection', 'KYC Rejection'), ('payment_release', 'Payment Release'), ('payment_refund', 'Payment Refund'), ('user_ban', 'User Ban'), ('user_unban', 'User Unban'), ('user_suspend', 'User Suspend'), ('user_activate', 'User Activate'), ('user_delete', 'User Delete'), ('settings_change', 'Settings Change'), ('admin_create', 'Admin Create'), ('admin_update', 'Admin Update'), ('admin_delete', 'Admin Delete'), ('job_update', 'Job Update'), ('job_cancel', 'Job Cancel'), ('ticket_reply', 'Ticket Reply'), ('ticket_close', 'Ticket Close'), ('report_review', 'Report Review'), ('faq_create', 'FAQ Create'), ('faq_update', 'FAQ Update'), ('faq_delete', 'FAQ Delete'), ('backjob_approve', 'Backjob Approve'), ('backjob_reject', 'Backjob Reject'), ('dispute_resolve', 'Dispute Resolve'), ('user_login', 'User Login'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Update')], help_text='Type of action performed', max_length=30),
        ),
    ]
