# Generated by Django 6.0 on 2025-12-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_certification_verification_logs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificationlog',
            new_name='certificati_certifi_eead3c_idx',
            old_name='certificati_certifi_idx',
        ),
        migrations.RenameIndex(
            model_name='certificationlog',
            new_name='certificati_workerI_adad02_idx',
            old_name='certificati_workerI_idx',
        ),
        migrations.RenameIndex(
            model_name='certificationlog',
            new_name='certificati_action_ea4a2f_idx',
            old_name='certificati_action_idx',
        ),
    ]
