# Generated by Django 6.0.1 on 2026-01-30 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_support_ticket_agency_fields'),
        ('adminpanel', '0012_enable_auto_approve_kyc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='agencyFK',
            field=models.ForeignKey(blank=True, help_text='Agency that submitted the ticket (if agency ticket)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticketType',
            field=models.CharField(choices=[('individual', 'Individual User'), ('agency', 'Agency')], default='individual', help_text='Whether ticket is from individual user or agency', max_length=15),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('account', 'Account Issues'), ('payment', 'Payment Issues'), ('technical', 'Technical Problems'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('general', 'General Inquiry'), ('kyc', 'KYC Verification'), ('employees', 'Employee Management'), ('jobs', 'Jobs & Invitations')], default='general', max_length=20),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticketType'], name='adminpanel__ticketT_a25d01_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['agencyFK'], name='adminpanel__agencyF_701033_idx'),
        ),
    ]
