# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_support_ticket_agency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='platform',
            field=models.CharField(
                choices=[('web', 'Web'), ('mobile', 'Mobile'), ('agency_portal', 'Agency Portal')],
                default='web',
                max_length=20,
                help_text='Platform where the ticket was created',
            ),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='deviceInfo',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Device information for mobile app tickets',
            ),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='appVersion',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                help_text='Mobile app version',
            ),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['platform'], name='support_ticket_platform_idx'),
        ),
    ]
