# Generated by Django 5.2.11 on 2026-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_supportticket_platform_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='adminpanel__platfor_2e4fb5_idx',
            old_name='support_ticket_platform_idx',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='deviceInfo',
            field=models.TextField(blank=True, help_text='Device/browser info (User-Agent)', null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='platform',
            field=models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App'), ('agency_portal', 'Agency Portal')], default='web', help_text='Platform where ticket was created', max_length=15),
        ),
    ]
