# Generated by Django 5.2.7 on 2025-10-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencykycsubmission',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='authorizedrepresentative',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencykycsubmission',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='agencykycsubmission',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='agencykycsubmission',
            name='submitted_by',
        ),
        migrations.CreateModel(
            name='AgencyKYC',
            fields=[
                ('agencyKycID', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=10)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=511)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accountFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_agency_kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyKycFile',
            fields=[
                ('fileID', models.BigAutoField(primary_key=True, serialize=False)),
                ('fileType', models.CharField(blank=True, choices=[('BUSINESS_PERMIT', 'business_permit'), ('REP_ID_FRONT', 'rep_id_front'), ('REP_ID_BACK', 'rep_id_back'), ('ADDRESS_PROOF', 'address_proof'), ('AUTH_LETTER', 'authorization_letter')], max_length=30, null=True)),
                ('fileURL', models.CharField(max_length=1000)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('fileSize', models.IntegerField(blank=True, null=True)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('agencyKyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agencykyc')),
            ],
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='AuthorizedRepresentative',
        ),
        migrations.DeleteModel(
            name='AgencyKYCSubmission',
        ),
    ]
