# Generated by Django 5.2.7 on 2025-10-30 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyEmployee',
            fields=[
                ('employeeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agency_employees',
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
