# Generated by Django 5.2.8 on 2025-11-11 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agencyemployee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyemployee',
            name='employeeOfTheMonth',
            field=models.BooleanField(default=False, help_text='Whether this employee is currently Employee of the Month'),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='employeeOfTheMonthDate',
            field=models.DateTimeField(blank=True, help_text='Date when employee was selected as EOTM', null=True),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='employeeOfTheMonthReason',
            field=models.TextField(blank=True, default='', help_text='Reason for selecting as Employee of the Month'),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Whether the employee is currently active'),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='lastRatingUpdate',
            field=models.DateTimeField(blank=True, help_text='Last time the rating was manually updated by agency owner', null=True),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='totalEarnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings generated by this employee', max_digits=10),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='totalJobsCompleted',
            field=models.IntegerField(default=0, help_text='Total number of jobs completed by this employee'),
        ),
        migrations.AddIndex(
            model_name='agencyemployee',
            index=models.Index(fields=['agency', 'isActive'], name='agency_empl_agency__4dc656_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyemployee',
            index=models.Index(fields=['agency', 'employeeOfTheMonth'], name='agency_empl_agency__8ae1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyemployee',
            index=models.Index(fields=['-rating'], name='agency_empl_rating_2ae8be_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyemployee',
            index=models.Index(fields=['-totalJobsCompleted'], name='agency_empl_totalJo_532418_idx'),
        ),
    ]
