# Generated by Django 5.2.11 on 2026-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_agencykyc_face_similarity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyemployee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
