# Generated by Django 5.2.6 on 2025-10-20 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_alter_workerproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProduct',
            fields=[
                ('productID', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priceUnit', models.CharField(choices=[('PIECE', 'Per Piece'), ('SET', 'Per Set'), ('LITER', 'Per Liter'), ('GALLON', 'Per Gallon'), ('KG', 'Per Kilogram'), ('METER', 'Per Meter'), ('HOUR', 'Per Hour'), ('SERVICE', 'Per Service')], default='PIECE', max_length=20)),
                ('inStock', models.BooleanField(default=True)),
                ('stockQuantity', models.IntegerField(blank=True, null=True)),
                ('productImage', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('categoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_products', to='accounts.specializations')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['workerID', '-createdAt'], name='profiles_wo_workerI_88e317_idx'), models.Index(fields=['categoryID', 'isActive'], name='profiles_wo_categor_4b810f_idx'), models.Index(fields=['isActive', 'inStock'], name='profiles_wo_isActiv_1c7e0a_idx')],
            },
        ),
    ]
