# Generated by Django 5.2.6 on 2025-10-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerproduct',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='workerproduct',
            name='profiles_wo_workerI_88e317_idx',
        ),
        migrations.RemoveIndex(
            model_name='workerproduct',
            name='profiles_wo_categor_4b810f_idx',
        ),
        migrations.RemoveIndex(
            model_name='workerproduct',
            name='profiles_wo_isActiv_1c7e0a_idx',
        ),
    ]
