# Generated by Django 5.2.7 on 2025-11-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_message_conversationid_remove_message_sender_and_more'),
        ('profiles', '0002_alter_workerproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastMessageText', models.TextField(blank=True, null=True)),
                ('lastMessageTime', models.DateTimeField(blank=True, null=True)),
                ('unreadCountClient', models.IntegerField(default=0)),
                ('unreadCountWorker', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_client', to='accounts.profile')),
                ('lastMessageSender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_messages_sent', to='accounts.profile')),
                ('relatedJobPosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_conversation', to='accounts.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_worker', to='accounts.profile')),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.BigAutoField(primary_key=True, serialize=False)),
                ('messageText', models.TextField()),
                ('messageType', models.CharField(choices=[('TEXT', 'Text'), ('SYSTEM', 'System'), ('LOCATION', 'Location'), ('IMAGE', 'Image'), ('FILE', 'File')], default='TEXT', max_length=10)),
                ('locationAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('locationLandmark', models.CharField(blank=True, max_length=255, null=True)),
                ('locationLatitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('locationLongitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('isRead', models.BooleanField(default=False)),
                ('readAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('conversationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='profiles.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.profile')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('attachmentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('fileURL', models.CharField(max_length=255)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('fileSize', models.IntegerField(blank=True, null=True)),
                ('fileType', models.CharField(blank=True, max_length=50, null=True)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('messageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='profiles.message')),
            ],
            options={
                'db_table': 'message_attachment',
                'ordering': ['uploadedAt'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', '-updatedAt'], name='conversatio_client__5b2f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['worker', '-updatedAt'], name='conversatio_worker__cc2b64_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['relatedJobPosting'], name='conversatio_related_6f5495_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='conversatio_status_7e2047_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('relatedJobPosting',), name='unique_job_conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversationID', 'createdAt'], name='message_convers_1671b3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-createdAt'], name='message_sender__33ec43_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['isRead'], name='message_isRead_b20976_idx'),
        ),
    ]
