# Generated by Django 5.2.7 on 2025-11-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_conversation_message_messageattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archivedByClient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='archivedByWorker',
            field=models.BooleanField(default=False),
        ),
    ]
