# Generated by Django 5.2.8 on 2025-11-30 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_job_assignedemployeeid_job_assignmentnotes_and_more'),
        ('profiles', '0004_add_archive_flags_to_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_agency', to='accounts.agency'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_worker', to='accounts.profile'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agency', '-updatedAt'], name='conversatio_agency__90e6b8_idx'),
        ),
    ]
