# Generated by Django 5.2.8 on 2025-11-30 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_job_assignedemployeeid_job_assignmentnotes_and_more'),
        ('profiles', '0005_add_agency_to_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='senderAgency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.agency'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.profile'),
        ),
    ]
