# Generated by Django 6.0 on 2025-12-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_team_conversation_support'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationparticipant',
            new_name='conversatio_convers_763591_idx',
            old_name='conv_part_conv_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationparticipant',
            new_name='conversatio_profile_7a3caa_idx',
            old_name='conv_part_profile_joined_idx',
        ),
    ]
