# Generated by Django 5.2.6 on 2025-09-29 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('specializationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('specializationName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('accountID', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('isVerified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('verifyToken', models.CharField(blank=True, max_length=255, null=True)),
                ('verifyTokenExpiry', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agencyId', models.BigAutoField(primary_key=True, serialize=False)),
                ('businessName', models.CharField(max_length=50)),
                ('businessDesc', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('accountFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileID', models.BigAutoField(primary_key=True, serialize=False)),
                ('profileImg', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=24)),
                ('lastName', models.CharField(max_length=24)),
                ('contactNum', models.CharField(max_length=11)),
                ('birthDate', models.DateField()),
                ('profileType', models.CharField(blank=True, choices=[('WORKER', 'Worker'), ('CLIENT', 'Client')], max_length=10, null=True)),
                ('accountFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=350)),
                ('totalJobsPosted', models.IntegerField()),
                ('clientRating', models.IntegerField(default=0)),
                ('profileID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='InterestedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile')),
                ('specializationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specializations')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=350)),
                ('workerRating', models.IntegerField(default=0)),
                ('totalEarningGross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availabilityStatus', models.CharField(blank=True, choices=[('AVAILABLE', 'available'), ('BUSY', 'busy'), ('OFFLINE', 'offline')], default='OFFLINE', max_length=10)),
                ('profileID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='workerSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experienceYears', models.IntegerField()),
                ('certification', models.CharField(max_length=120)),
                ('specializationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specializations')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workerprofile')),
            ],
        ),
    ]
