# Generated by Django 5.2.6 on 2025-09-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountID', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('isVerified', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileID', models.BigAutoField(primary_key=True, serialize=False)),
                ('profileImg', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=24)),
                ('lastName', models.CharField(max_length=24)),
                ('contactNum', models.CharField(max_length=11)),
                ('birthDate', models.DateField()),
                ('profileType', models.CharField(blank=True, choices=[('WORKER', 'Worker'), ('CLIENT', 'Client')], max_length=10, null=True)),
                ('accountFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
    ]
