# Generated by Django 5.2.6 on 2025-10-04 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_city_accounts_country_accounts_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='accountFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='kyc',
            fields=[
                ('kycID', models.BigAutoField(primary_key=True, serialize=False)),
                ('kycStatus', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('Rejected', 'rejected')], default='PENDING', max_length=10)),
                ('reviewedAt', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(max_length=211)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accountFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='kycFiles',
            fields=[
                ('kycFileID', models.BigAutoField(primary_key=True, serialize=False)),
                ('fileType', models.CharField(blank=True, choices=[('FRONTID', 'frontid'), ('BACKID', 'backid'), ('CLEARANCE', 'clearance'), ('SELFIE', 'selfie')], default=None, max_length=10)),
                ('idType', models.CharField(blank=True, choices=[('PASSPORT', 'passport'), ('NATIONALID', 'nationalid'), ('UMID', 'umid'), ('PHILHEALTH', 'philhealth')], max_length=10, null=True)),
                ('fileURL', models.CharField(max_length=255)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('fileSize', models.IntegerField(blank=True, null=True)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('kycID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kyc')),
            ],
        ),
    ]
