# Generated by Django 5.2.6 on 2025-10-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_agency_accountfk_kyc_kycfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycfiles',
            name='idType',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'passport'), ('NATIONALID', 'nationalid'), ('UMID', 'umid'), ('PHILHEALTH', 'philhealth'), ('DRIVERSLICENSE', 'driverslicense'), ('POLICE', 'police'), ('NBI', 'nbi')], max_length=20, null=True),
        ),
    ]
