# Generated by Django 5.2.6 on 2025-09-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_groups_accounts_is_active_accounts_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='verifyToken',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='verifyTokenExpiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
