# Generated by Django 5.2.6 on 2025-09-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_verifytoken_accounts_verifytokenexpiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='verifyToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
