# Generated by Django 5.2.6 on 2025-10-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_kycfiles_idtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycfiles',
            name='fileType',
        ),
    ]
