# Generated by Django 5.2.6 on 2025-10-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_kycfiles_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='KYCVerified',
            field=models.BooleanField(default=False),
        ),
    ]
