# Generated by Django 5.2.6 on 2025-10-07 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_kycverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('notificationType', models.CharField(choices=[('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('MESSAGE', 'Message'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('relatedKYCLogID', models.BigIntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('readAt', models.DateTimeField(blank=True, null=True)),
                ('accountFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['accountFK', '-createdAt'], name='accounts_no_account_225939_idx'), models.Index(fields=['accountFK', 'isRead'], name='accounts_no_account_992e61_idx')],
            },
        ),
    ]
