# Generated by Django 5.2.6 on 2025-10-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Current latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_sharing_enabled',
            field=models.BooleanField(default=False, help_text='Whether user has enabled location sharing'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last location update', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Current longitude coordinate', max_digits=11, null=True),
        ),
    ]
