# Generated by Django 5.2.6 on 2025-10-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_latitude_profile_location_sharing_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.CharField(max_length=500),
        ),
    ]
