# Generated by Django 5.2.6 on 2025-10-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('jobPostingID', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('expectedDuration', models.CharField(blank=True, max_length=100, null=True)),
                ('urgency', models.CharField(choices=[('LOW', 'Low - Flexible timing'), ('MEDIUM', 'Medium - Within a week'), ('HIGH', 'High - ASAP')], default='MEDIUM', max_length=10)),
                ('preferredStartDate', models.DateField(blank=True, null=True)),
                ('materialsNeeded', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='accounts.specializations')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='accounts.clientprofile')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='JobPostingPhoto',
            fields=[
                ('photoID', models.BigAutoField(primary_key=True, serialize=False)),
                ('photoURL', models.CharField(max_length=255)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('fileSize', models.IntegerField(blank=True, null=True)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('jobPostingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.jobposting')),
            ],
            options={
                'ordering': ['uploadedAt'],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['clientID', '-createdAt'], name='accounts_jo_clientI_0890ec_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', '-createdAt'], name='accounts_jo_status_8e7e04_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['categoryID', 'status'], name='accounts_jo_categor_82a59e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['urgency', '-createdAt'], name='accounts_jo_urgency_a0aa81_idx'),
        ),
    ]
