# Generated by Django 5.2.6 on 2025-10-18 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jobposting_jobpostingphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversationType', models.CharField(choices=[('GENERAL', 'General'), ('INVITE', 'Invite'), ('APPLICATION', 'Application')], default='GENERAL', max_length=15)),
                ('lastMessageText', models.TextField(blank=True, null=True)),
                ('lastMessageTime', models.DateTimeField(blank=True, null=True)),
                ('unreadCountParticipant1', models.IntegerField(default=0)),
                ('unreadCountParticipant2', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('lastMessageSender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant1', to=settings.AUTH_USER_MODEL)),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant2', to=settings.AUTH_USER_MODEL)),
                ('relatedJobPosting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.jobposting')),
            ],
            options={
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.BigAutoField(primary_key=True, serialize=False)),
                ('messageText', models.TextField()),
                ('messageType', models.CharField(choices=[('TEXT', 'Text'), ('SYSTEM', 'System'), ('LOCATION', 'Location'), ('IMAGE', 'Image'), ('FILE', 'File')], default='TEXT', max_length=10)),
                ('locationAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('locationLandmark', models.CharField(blank=True, max_length=255, null=True)),
                ('locationLatitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('locationLongitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('isRead', models.BooleanField(default=False)),
                ('readAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('conversationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('attachmentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('fileURL', models.CharField(max_length=255)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('fileSize', models.IntegerField(blank=True, null=True)),
                ('fileType', models.CharField(blank=True, max_length=50, null=True)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('messageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.message')),
            ],
            options={
                'ordering': ['uploadedAt'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant1', '-updatedAt'], name='accounts_co_partici_2c113d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant2', '-updatedAt'], name='accounts_co_partici_7c2e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['relatedJobPosting'], name='accounts_co_related_d36217_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant1', 'participant2'), name='unique_conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversationID', 'createdAt'], name='accounts_me_convers_89b84b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-createdAt'], name='accounts_me_sender__e50d11_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['isRead'], name='accounts_me_isRead_4e16c9_idx'),
        ),
    ]
