# Generated by Django 5.2.6 on 2025-10-18 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_conversation_message_messageattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletID', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accountFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('transactionType', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('EARNING', 'Earning'), ('FEE', 'Platform Fee')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceAfter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('referenceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentMethod', models.CharField(blank=True, choices=[('WALLET', 'Wallet'), ('GCASH', 'GCash'), ('MAYA', 'Maya'), ('CARD', 'Credit/Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], default='WALLET', max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('relatedJobPosting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.jobposting')),
                ('walletID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['accountFK'], name='accounts_wa_account_5c6166_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['walletID', '-createdAt'], name='accounts_tr_walletI_417c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transactionType', '-createdAt'], name='accounts_tr_transac_c2a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-createdAt'], name='accounts_tr_status_c95c77_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['referenceNumber'], name='accounts_tr_referen_0f1695_idx'),
        ),
    ]
