# Generated by Django 5.2.6 on 2025-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_wallet_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoiceURL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='xenditExternalID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='xenditInvoiceID',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='xenditPaymentChannel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='xenditPaymentID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='xenditPaymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['xenditInvoiceID'], name='accounts_tr_xenditI_348817_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['xenditExternalID'], name='accounts_tr_xenditE_a6ad2c_idx'),
        ),
    ]
