# Generated by Django 5.2.6 on 2025-10-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_workerproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerproduct',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='workerproduct',
            name='accounts_wo_workerI_c2548c_idx',
        ),
        migrations.RemoveIndex(
            model_name='workerproduct',
            name='accounts_wo_categor_3c6b77_idx',
        ),
        migrations.RemoveIndex(
            model_name='workerproduct',
            name='accounts_wo_isActiv_3f2c5c_idx',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='inStock',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='priceUnit',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='productImage',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='stockQuantity',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='workerproduct',
            name='workerID',
        ),
        migrations.AddField(
            model_name='workerproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
