# Generated by Django 5.2.6 on 2025-10-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_workerproduct_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerProduct',
        ),
    ]
