# Generated by Django 5.2.7 on 2025-10-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_workerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='contactNumber',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
