# Generated by Django 5.2.7 on 2025-10-30 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_agency_contactnumber'),
    ]

    operations = [
        # Rename JobPosting model to Job
        migrations.RenameModel(
            old_name='JobPosting',
            new_name='Job',
        ),
        # Rename primary key field
        migrations.RenameField(
            model_name='job',
            old_name='jobPostingID',
            new_name='jobID',
        ),
        # Add new fields
        migrations.AddField(
            model_name='job',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cancellationReason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='assignedWorkerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='accounts.workerprofile'),
        ),
        # Update table name
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
        # Update foreign key related names
        migrations.AlterField(
            model_name='job',
            name='categoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.specializations'),
        ),
        migrations.AlterField(
            model_name='job',
            name='clientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.clientprofile'),
        ),
        # Rename JobPostingPhoto to JobPhoto
        migrations.RenameModel(
            old_name='JobPostingPhoto',
            new_name='JobPhoto',
        ),
        # Rename the foreign key field in JobPhoto
        migrations.RenameField(
            model_name='jobphoto',
            old_name='jobPostingID',
            new_name='jobID',
        ),
        # Update JobPhoto table name and options
        migrations.AlterModelOptions(
            name='jobphoto',
            options={'ordering': ['-uploadedAt']},
        ),
        migrations.AlterModelTable(
            name='jobphoto',
            table='job_photos',
        ),
        # Remove fileSize field (if it was in original JobPostingPhoto but not in new JobPhoto)
        migrations.RemoveField(
            model_name='jobphoto',
            name='fileSize',
        ),
        # Update foreign key relationships for other models
        migrations.AlterField(
            model_name='conversation',
            name='relatedJobPosting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.job'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='relatedJobPosting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.job'),
        ),
        # Create JobLog model
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('logID', models.BigAutoField(primary_key=True, serialize=False)),
                ('oldStatus', models.CharField(blank=True, max_length=15, null=True)),
                ('newStatus', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('changedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_status_changes', to=settings.AUTH_USER_MODEL)),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.job')),
            ],
            options={
                'db_table': 'job_logs',
                'ordering': ['-createdAt'],
            },
        ),
        # Add indexes for Job model
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['clientID', '-createdAt'], name='jobs_clientI_03c7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-createdAt'], name='jobs_status_9d014c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['categoryID', 'status'], name='jobs_categor_d47dee_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['urgency', '-createdAt'], name='jobs_urgency_b2dcee_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assignedWorkerID', 'status'], name='jobs_assigne_cc625f_idx'),
        ),
        # Add indexes for JobLog model
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['jobID', '-createdAt'], name='job_logs_jobID_i_b5c46a_idx'),
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['newStatus', '-createdAt'], name='job_logs_newStat_d67ac4_idx'),
        ),
    ]
