# Generated by Django 5.2.7 on 2025-10-30 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_agency_contactnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='clientID',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobID', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('expectedDuration', models.CharField(blank=True, max_length=100, null=True)),
                ('urgency', models.CharField(choices=[('LOW', 'Low - Flexible timing'), ('MEDIUM', 'Medium - Within a week'), ('HIGH', 'High - ASAP')], default='MEDIUM', max_length=10)),
                ('preferredStartDate', models.DateField(blank=True, null=True)),
                ('materialsNeeded', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('cancellationReason', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('assignedWorkerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='accounts.workerprofile')),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.specializations')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.clientprofile')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.AlterField(
            model_name='conversation',
            name='relatedJobPosting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.job'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='relatedJobPosting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.job'),
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('logID', models.BigAutoField(primary_key=True, serialize=False)),
                ('oldStatus', models.CharField(blank=True, max_length=15, null=True)),
                ('newStatus', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('changedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_status_changes', to=settings.AUTH_USER_MODEL)),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.job')),
            ],
            options={
                'db_table': 'job_logs',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('photoID', models.BigAutoField(primary_key=True, serialize=False)),
                ('photoURL', models.CharField(max_length=255)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.job')),
            ],
            options={
                'db_table': 'job_photos',
                'ordering': ['-uploadedAt'],
            },
        ),
        migrations.DeleteModel(
            name='JobPostingPhoto',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['clientID', '-createdAt'], name='jobs_clientI_03c7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-createdAt'], name='jobs_status_9d014c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['categoryID', 'status'], name='jobs_categor_d47dee_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['urgency', '-createdAt'], name='jobs_urgency_b2dcee_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assignedWorkerID', 'status'], name='jobs_assigne_cc625f_idx'),
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['jobID', '-createdAt'], name='job_logs_jobID_i_b5c46a_idx'),
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['newStatus', '-createdAt'], name='job_logs_newStat_d67ac4_idx'),
        ),
    ]
