# Generated by Django 5.2.7 on 2025-10-30 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_job_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('applicationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('proposalMessage', models.TextField()),
                ('proposedBudget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimatedDuration', models.CharField(blank=True, max_length=100, null=True)),
                ('budgetOption', models.CharField(choices=[('ACCEPT', "Accept Client's Budget"), ('NEGOTIATE', 'Negotiate Different Budget')], default='NEGOTIATE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.job')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='accounts.workerprofile')),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['jobID', '-createdAt'], name='job_applica_jobID_i_c676f8_idx'), models.Index(fields=['workerID', '-createdAt'], name='job_applica_workerI_027e10_idx'), models.Index(fields=['status', '-createdAt'], name='job_applica_status_08790f_idx')],
                'constraints': [models.UniqueConstraint(fields=('jobID', 'workerID'), name='unique_job_application')],
            },
        ),
    ]
