# Generated by Django 5.2.7 on 2025-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializations',
            name='averageProjectCostMax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='specializations',
            name='averageProjectCostMin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='specializations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specializations',
            name='minimumRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='specializations',
            name='rateType',
            field=models.CharField(default='hourly', max_length=20),
        ),
        migrations.AddField(
            model_name='specializations',
            name='skillLevel',
            field=models.CharField(default='intermediate', max_length=20),
        ),
        migrations.AlterModelTable(
            name='specializations',
            table='specializations',
        ),
    ]
