# Generated by Django 5.2.7 on 2025-10-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_specializations_averageprojectcostmax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDispute',
            fields=[
                ('disputeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('disputedBy', models.CharField(choices=[('CLIENT', 'Client'), ('WORKER', 'Worker')], max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('jobAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disputedAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolvedDate', models.DateTimeField(blank=True, null=True)),
                ('assignedTo', models.CharField(blank=True, max_length=200, null=True)),
                ('openedDate', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='accounts.job')),
            ],
            options={
                'db_table': 'job_disputes',
                'ordering': ['-openedDate'],
                'indexes': [models.Index(fields=['jobID', '-openedDate'], name='job_dispute_jobID_i_5435ed_idx'), models.Index(fields=['status', '-openedDate'], name='job_dispute_status_3f7a05_idx'), models.Index(fields=['priority', '-openedDate'], name='job_dispute_priorit_40a747_idx')],
            },
        ),
    ]
