# Generated by Django 5.2.7 on 2025-10-30 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_jobdispute'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('reviewID', models.BigAutoField(primary_key=True, serialize=False)),
                ('reviewerType', models.CharField(choices=[('CLIENT', 'Client'), ('WORKER', 'Worker')], max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FLAGGED', 'Flagged'), ('HIDDEN', 'Hidden'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('isFlagged', models.BooleanField(default=False)),
                ('flagReason', models.TextField(blank=True, null=True)),
                ('flaggedAt', models.DateTimeField(blank=True, null=True)),
                ('helpfulCount', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('flaggedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_reviews', to=settings.AUTH_USER_MODEL)),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.job')),
                ('revieweeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_reviews',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['jobID', '-createdAt'], name='job_reviews_jobID_i_fe8bbe_idx'), models.Index(fields=['reviewerID', '-createdAt'], name='job_reviews_reviewe_67461b_idx'), models.Index(fields=['revieweeID', '-createdAt'], name='job_reviews_reviewe_f47e2e_idx'), models.Index(fields=['status', '-createdAt'], name='job_reviews_status_d2c214_idx'), models.Index(fields=['isFlagged', '-createdAt'], name='job_reviews_isFlagg_8bb65d_idx')],
                'constraints': [models.UniqueConstraint(fields=('jobID', 'reviewerID'), name='unique_job_reviewer')],
            },
        ),
    ]
