# Generated by Django 5.2.7 on 2025-11-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_jobreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversationID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='messageID',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
