# Generated by Django 5.2.6 on 2025-11-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clientMarkedComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='clientMarkedCompleteAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='workerMarkedComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='workerMarkedCompleteAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15),
        ),
    ]
