# Generated by Django 5.2.7 on 2025-11-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_job_clientmarkedcomplete_job_clientmarkedcompleteat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='escrowAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount held in escrow (50% downpayment)', max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='escrowPaid',
            field=models.BooleanField(default=False, help_text='Whether the escrow downpayment has been paid'),
        ),
        migrations.AddField(
            model_name='job',
            name='escrowPaidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='remainingPayment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining 50% to be paid upon completion', max_digits=10),
        ),
    ]
