# Generated by Django 5.2.7 on 2025-11-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_escrow_fields_to_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remainingPaymentPaid',
            field=models.BooleanField(default=False, help_text='Whether the remaining 50% payment has been paid'),
        ),
        migrations.AddField(
            model_name='job',
            name='remainingPaymentPaidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
