# Generated by Django 5.2.6 on 2025-11-06 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_payment_method_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cashPaymentApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='cashPaymentApprovedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cashPaymentApprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='cashProofUploadedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='paymentMethodSelectedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
