# Generated by Django 5.2.8 on 2025-11-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification_updates'),
        ('accounts', '0029_alter_job_cashpaymentapproved_and_more'),
    ]

    operations = [
    ]
