# Generated by Django 5.2.8 on 2025-11-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_add_agency_acceptance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
