# Generated by Django 5.2.8 on 2025-11-10 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='accountType',
        ),
        migrations.RemoveField(
            model_name='job',
            name='acceptedByAgency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='agencyAcceptedAt',
        ),
        migrations.AddField(
            model_name='job',
            name='agenciesOnly',
            field=models.BooleanField(default=False, help_text='Only agencies can be requested (blocks individual workers)'),
        ),
        migrations.AddField(
            model_name='job',
            name='agenciesPreferred',
            field=models.BooleanField(default=False, help_text='Client prefers agencies over individual workers'),
        ),
        migrations.AddField(
            model_name='job',
            name='assignedAgencyFK',
            field=models.ForeignKey(blank=True, help_text='Agency assigned to this job (when request accepted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='job',
            name='minimumAgencyRating',
            field=models.FloatField(blank=True, help_text='Minimum average rating for agencies (0.0-5.0)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requiredCertifications',
            field=models.JSONField(blank=True, default=list, help_text='List of required certification IDs for agencies'),
        ),
        migrations.AddField(
            model_name='job',
            name='serviceLevel',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STANDARD', help_text='Expected service level from agency', max_length=20),
        ),
        migrations.CreateModel(
            name='AgencyJobRequest',
            fields=[
                ('requestID', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('clientMessage', models.TextField(help_text='Message from client explaining why they want this agency')),
                ('agencyResponse', models.TextField(blank=True, default='', help_text="Agency's response (acceptance note or decline reason)")),
                ('requestedAt', models.DateTimeField(auto_now_add=True)),
                ('respondedAt', models.DateTimeField(blank=True, null=True)),
                ('expiresAt', models.DateTimeField(help_text='Request expires after 7 days if not responded')),
                ('isUrgent', models.BooleanField(default=False, help_text='Marked as urgent by client')),
                ('clientBudgetFlexible', models.BooleanField(default=False, help_text='Client indicated budget is negotiable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencyFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='accounts.agency')),
                ('clientFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('jobFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_requests', to='accounts.job')),
            ],
            options={
                'db_table': 'agency_job_requests',
                'ordering': ['-requestedAt'],
                'indexes': [models.Index(fields=['agencyFK', 'status', '-requestedAt'], name='agency_job__agencyF_ac36c5_idx'), models.Index(fields=['clientFK', 'status'], name='agency_job__clientF_f7f545_idx'), models.Index(fields=['status', 'expiresAt'], name='agency_job__status_183325_idx')],
                'unique_together': {('jobFK', 'agencyFK')},
            },
        ),
    ]
