# Generated by Django 5.2.8 on 2025-11-10 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_accounts_accounttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='agenciesOnly',
        ),
        migrations.RemoveField(
            model_name='job',
            name='agenciesPreferred',
        ),
        migrations.RemoveField(
            model_name='job',
            name='minimumAgencyRating',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requiredCertifications',
        ),
        migrations.RemoveField(
            model_name='job',
            name='serviceLevel',
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('LISTING', 'Job Listing (Open for applications)'), ('INVITE', 'Direct Invite/Hire (Worker or Agency)')], default='LISTING', help_text='LISTING = open job post, INVITE = direct hire', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='assignedAgencyFK',
            field=models.ForeignKey(blank=True, help_text='Agency assigned to this job (for agency hires)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='accounts.agency'),
        ),
        migrations.AlterField(
            model_name='job',
            name='assignedWorkerID',
            field=models.ForeignKey(blank=True, help_text='Worker assigned to this job (for individual workers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='accounts.workerprofile'),
        ),
        migrations.DeleteModel(
            name='AgencyJobRequest',
        ),
    ]
