# Generated by Django 5.2.8 on 2025-11-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_worker_phase1_profile_enhancements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workercertification',
            new_name='worker_cert_workerI_6b96e2_idx',
            old_name='worker_cert_worker_date_idx',
        ),
        migrations.RenameIndex(
            model_name='workercertification',
            new_name='worker_cert_expiry__fe5d02_idx',
            old_name='worker_cert_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='workerportfolio',
            new_name='worker_port_workerI_7d29c4_idx',
            old_name='worker_port_worker_order_idx',
        ),
    ]
