# Generated by Django 5.2.8 on 2025-11-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_rename_worker_cert_worker_date_idx_worker_cert_workeri_6b96e2_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='kycStatus',
            new_name='kyc_status',
        ),
        migrations.RenameField(
            model_name='workerprofile',
            old_name='availabilityStatus',
            new_name='availability_status',
        ),
    ]
