# Generated by Django 5.2.8 on 2025-11-13 12:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_rename_kycstatus_kyc_kyc_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='totalEarningGross',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
