# Generated by Django 5.2.8 on 2025-11-15 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_workerprofile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('settingsID', models.BigAutoField(primary_key=True, serialize=False)),
                ('pushEnabled', models.BooleanField(default=True)),
                ('soundEnabled', models.BooleanField(default=True)),
                ('jobUpdates', models.BooleanField(default=True)),
                ('messages', models.BooleanField(default=True)),
                ('payments', models.BooleanField(default=True)),
                ('reviews', models.BooleanField(default=True)),
                ('kycUpdates', models.BooleanField(default=True)),
                ('doNotDisturbStart', models.TimeField(blank=True, null=True)),
                ('doNotDisturbEnd', models.TimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accountFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('tokenID', models.BigAutoField(primary_key=True, serialize=False)),
                ('pushToken', models.CharField(max_length=500, unique=True)),
                ('deviceType', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], default='android', max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('lastUsed', models.DateTimeField(auto_now=True)),
                ('accountFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-lastUsed'],
                'indexes': [models.Index(fields=['accountFK', 'isActive'], name='accounts_pu_account_956577_idx'), models.Index(fields=['pushToken'], name='accounts_pu_pushTok_d919a9_idx')],
            },
        ),
    ]
