# Generated by Django 5.2.8 on 2025-11-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_notificationsettings_pushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zipCode', models.CharField(blank=True, max_length=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='accounts_ci_name_3741a5_idx'), models.Index(fields=['province'], name='accounts_ci_provinc_3bc3e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('barangayID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('zipCode', models.CharField(blank=True, max_length=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='accounts.city')),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'name'], name='accounts_ba_city_id_e22fce_idx'), models.Index(fields=['name'], name='accounts_ba_name_b64a2f_idx')],
                'unique_together': {('name', 'city')},
            },
        ),
    ]
