# Generated by Django 5.2.8 on 2025-11-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_add_city_barangay_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerMaterial',
            fields=[
                ('materialID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Material/product name (e.g., 'Cement 40kg bag', 'PVC Pipe 1 inch')", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the material/product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PHP', max_digits=10)),
                ('unit', models.CharField(default='piece', help_text="Unit of measurement (e.g., 'piece', 'kg', 'meter', 'bag', 'box')", max_length=50)),
                ('image_url', models.CharField(blank=True, default='', help_text='Supabase URL to product image', max_length=1000)),
                ('is_available', models.BooleanField(default=True, help_text='Whether material is currently available for sale')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.workerprofile')),
            ],
            options={
                'db_table': 'worker_materials',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['workerID', 'is_available'], name='worker_mate_workerI_77a627_idx'), models.Index(fields=['name'], name='worker_mate_name_b9fee4_idx')],
            },
        ),
    ]
