# Generated by Django 5.2.8 on 2025-11-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_workermaterial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clientConfirmedWorkStarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='clientConfirmedWorkStartedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
