# Generated by Django 5.2.8 on 2025-11-24 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_job_clientconfirmedworkstarted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='banned_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='suspended_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
