# Generated by Django 5.2.8 on 2025-11-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_job_assigned_employee_tracking'),
        ('accounts', '0046_accounts_banned_at_accounts_banned_by_and_more'),
    ]

    operations = [
    ]
