# Generated by Django 5.2.8 on 2025-11-26 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_merge_20251125_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodType', models.CharField(choices=[('GCASH', 'GCash'), ('BANK', 'Bank Account')], max_length=10)),
                ('accountName', models.CharField(max_length=255)),
                ('accountNumber', models.CharField(max_length=50)),
                ('bankName', models.CharField(blank=True, max_length=100, null=True)),
                ('isPrimary', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-isPrimary', '-createdAt'],
            },
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_assigned_employee_status_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='assignedEmployeeID',
        ),
        migrations.RemoveField(
            model_name='job',
            name='assignmentNotes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employeeAssignedAt',
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='accountFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
    ]
