# Generated by Django 5.2.8 on 2025-11-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_userpaymentmethod_and_more'),
        ('agency', '0003_agencyemployee_employeeofthemonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assignedEmployeeID',
            field=models.ForeignKey(blank=True, help_text='Specific agency employee assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='agency.agencyemployee'),
        ),
        migrations.AddField(
            model_name='job',
            name='assignmentNotes',
            field=models.TextField(blank=True, help_text='Notes from agency about this assignment', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employeeAssignedAt',
            field=models.DateTimeField(blank=True, help_text='When employee was assigned by agency', null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assignedEmployeeID', 'status'], name='job_assign_emp_status_idx'),
        ),
    ]
