# Generated by Django 5.2.8 on 2025-11-30 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_job_assignedemployeeid_job_assignmentnotes_and_more'),
        ('agency', '0003_agencyemployee_employeeofthemonth_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobreview',
            name='unique_job_reviewer',
        ),
        migrations.AddField(
            model_name='jobreview',
            name='revieweeAgencyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='jobreview',
            name='revieweeEmployeeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='agency.agencyemployee'),
        ),
        migrations.AlterField(
            model_name='jobreview',
            name='revieweeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobreview',
            index=models.Index(fields=['revieweeEmployeeID', '-createdAt'], name='job_reviews_reviewe_c3a832_idx'),
        ),
        migrations.AddIndex(
            model_name='jobreview',
            index=models.Index(fields=['revieweeAgencyID', '-createdAt'], name='job_reviews_reviewe_1276ae_idx'),
        ),
    ]
