# Generated by Django 5.2.8 on 2025-11-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_multi_employee_assignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobemployeeassignment',
            new_name='job_employe_job_id_2d7113_idx',
            old_name='job_employe_job_id_f1c2e3_idx',
        ),
        migrations.RenameIndex(
            model_name='jobemployeeassignment',
            new_name='job_employe_employe_5d922f_idx',
            old_name='job_employe_employe_d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='employeeAssignedAt',
            field=models.DateTimeField(blank=True, help_text='When first employee was assigned by agency', null=True),
        ),
    ]
