# Generated by Django 5.2.8 - Module 6 KYC Enhancements

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_rename_job_employe_job_id_f1c2e3_idx_job_employe_job_id_2d7113_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='rejectionCategory',
            field=models.CharField(
                blank=True,
                choices=[
                    ('INVALID_DOCUMENT', 'Invalid Document'),
                    ('EXPIRED_DOCUMENT', 'Expired Document'),
                    ('UNCLEAR_IMAGE', 'Unclear/Blurry Image'),
                    ('MISMATCH_INFO', 'Information Mismatch'),
                    ('INCOMPLETE', 'Incomplete Submission'),
                    ('OTHER', 'Other'),
                ],
                help_text='Category of rejection reason',
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='kyc',
            name='rejectionReason',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Detailed rejection reason for the user',
            ),
        ),
        migrations.AddField(
            model_name='kyc',
            name='resubmissionCount',
            field=models.IntegerField(
                default=0,
                help_text='Number of times the user has resubmitted KYC documents',
            ),
        ),
        migrations.AddField(
            model_name='kyc',
            name='maxResubmissions',
            field=models.IntegerField(
                default=3,
                help_text='Maximum allowed resubmission attempts',
            ),
        ),
    ]
