# Generated by Django 5.2.8 on 2025-12-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_kyc_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreview',
            name='reviewerType',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('WORKER', 'Worker'), ('AGENCY', 'Agency')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationType',
            field=models.CharField(choices=[('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('AGENCY_KYC_APPROVED', 'Agency KYC Approved'), ('AGENCY_KYC_REJECTED', 'Agency KYC Rejected'), ('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_ACCEPTED', 'Application Accepted'), ('APPLICATION_REJECTED', 'Application Rejected'), ('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED_WORKER', 'Job Marked Complete by Worker'), ('JOB_COMPLETED_CLIENT', 'Job Approved by Client'), ('JOB_CANCELLED', 'Job Cancelled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('ESCROW_PAID', 'Escrow Payment Confirmed'), ('REMAINING_PAYMENT_PAID', 'Final Payment Confirmed'), ('PAYMENT_RELEASED', 'Payment Released'), ('MESSAGE', 'New Message'), ('REVIEW_RECEIVED', 'Review Received'), ('BACKJOB_REQUESTED', 'Backjob Requested'), ('BACKJOB_APPROVED', 'Backjob Approved'), ('BACKJOB_REJECTED', 'Backjob Rejected'), ('BACKJOB_COMPLETED', 'Backjob Completed'), ('SYSTEM', 'System')], default='SYSTEM', max_length=50),
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('evidenceID', models.BigAutoField(primary_key=True, serialize=False)),
                ('imageURL', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('disputeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='accounts.jobdispute')),
                ('uploadedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute_evidence',
                'ordering': ['-createdAt'],
            },
        ),
    ]
