# Generated by Django 5.2.8 on 2025-12-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_dispute_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='activeJobsCount',
            field=models.IntegerField(default=0),
        ),
    ]
