# Generated by Django 5.2.8 on 2025-12-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_add_activejobscount_to_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='newStatus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='oldStatus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
