# Generated by Django 5.2.8 on 2025-12-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_increase_joblog_status_length'),
        ('agency', '0004_kyc_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreview',
            name='revieweeProfileID',
            field=models.ForeignKey(blank=True, help_text='The specific profile (WORKER or CLIENT) that received this review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.profile'),
        ),
        migrations.AddIndex(
            model_name='jobreview',
            index=models.Index(fields=['revieweeProfileID', '-createdAt'], name='job_reviews_reviewe_504347_idx'),
        ),
    ]
