# Generated by Django 5.2.8 on 2025-12-02 14:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_add_reviewee_profile_to_jobreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='reservedBalance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
