# Generated by Django 5.2.8 on 2025-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_add_wallet_reserved_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdispute',
            name='backjobStarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='backjobStartedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='clientConfirmedBackjob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='clientConfirmedBackjobAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='workerMarkedBackjobComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='workerMarkedBackjobCompleteAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
