# Generated by AI Agent on 2025-12-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_backjob_workflow_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdispute',
            name='termsAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='termsVersion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='termsAcceptedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
