# Generated by Django 6.0 on 2025-12-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_jobdispute_terms_acceptance_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='workercertification',
            name='specializationID',
            field=models.ForeignKey(blank=True, help_text='The specific skill this certification is for (e.g., Plumbing, Electrical)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='accounts.workerspecialization'),
        ),
        migrations.CreateModel(
            name='ReviewSkillTag',
            fields=[
                ('tagID', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('reviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tags', to='accounts.jobreview')),
                ('workerSpecializationID', models.ForeignKey(help_text="The specific skill being tagged (from worker's skill list)", on_delete=django.db.models.deletion.CASCADE, related_name='review_tags', to='accounts.workerspecialization')),
            ],
            options={
                'db_table': 'review_skill_tags',
                'indexes': [models.Index(fields=['reviewID'], name='review_skil_reviewI_f86a86_idx'), models.Index(fields=['workerSpecializationID'], name='review_skil_workerS_587697_idx')],
                'unique_together': {('reviewID', 'workerSpecializationID')},
            },
        ),
    ]
