# Generated by Django 6.0 on 2025-12-10 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_worker_skills_certifications_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreview',
            name='rating_communication',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Communication rating', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='jobreview',
            name='rating_professionalism',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Professionalism rating', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='jobreview',
            name='rating_punctuality',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Punctuality rating', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='jobreview',
            name='rating_quality',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quality of work rating', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='jobreview',
            name='rating',
            field=models.DecimalField(decimal_places=2, help_text='Overall rating (auto-calculated as average of criteria)', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationType',
            field=models.CharField(choices=[('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('AGENCY_KYC_APPROVED', 'Agency KYC Approved'), ('AGENCY_KYC_REJECTED', 'Agency KYC Rejected'), ('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_ACCEPTED', 'Application Accepted'), ('APPLICATION_REJECTED', 'Application Rejected'), ('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED_WORKER', 'Job Marked Complete by Worker'), ('JOB_COMPLETED_CLIENT', 'Job Approved by Client'), ('JOB_CANCELLED', 'Job Cancelled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('ESCROW_PAID', 'Escrow Payment Confirmed'), ('REMAINING_PAYMENT_PAID', 'Final Payment Confirmed'), ('PAYMENT_RELEASED', 'Payment Released'), ('MESSAGE', 'New Message'), ('REVIEW_RECEIVED', 'Review Received'), ('BACKJOB_REQUESTED', 'Backjob Requested'), ('BACKJOB_APPROVED', 'Backjob Approved'), ('BACKJOB_REJECTED', 'Backjob Rejected'), ('BACKJOB_COMPLETED', 'Backjob Completed'), ('CERTIFICATION_APPROVED', 'Certification Approved'), ('CERTIFICATION_REJECTED', 'Certification Rejected'), ('SYSTEM', 'System')], default='SYSTEM', max_length=50),
        ),
    ]
