# Generated by Django 6.0 on 2025-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_team_mode_multi_skill_workers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='job_applica_applied_237261_idx',
            old_name='job_app_skill_slot_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobskillslot',
            new_name='job_skill_s_jobID_i_04a042_idx',
            old_name='job_skill_s_jobID_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobskillslot',
            new_name='job_skill_s_special_8c143c_idx',
            old_name='job_skill_s_spec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobworkerassignment',
            new_name='job_worker__jobID_i_aacfe5_idx',
            old_name='job_worker_job_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobworkerassignment',
            new_name='job_worker__workerI_574455_idx',
            old_name='job_worker_worker_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobworkerassignment',
            new_name='job_worker__skillSl_c608db_idx',
            old_name='job_worker_slot_pos_idx',
        ),
        migrations.AlterField(
            model_name='jobskillslot',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open - Accepting Applications'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Fully Filled'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
