# Generated by Django 6.0 on 2025-12-11 14:09
# Universal job fields for ML price prediction accuracy

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_payment_buffer_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_scope',
            field=models.CharField(
                choices=[
                    ('MINOR_REPAIR', 'Minor Repair'),
                    ('MODERATE_PROJECT', 'Moderate Project'),
                    ('MAJOR_RENOVATION', 'Major Renovation'),
                ],
                default='MINOR_REPAIR',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_level_required',
            field=models.CharField(
                choices=[
                    ('ENTRY', 'Entry Level'),
                    ('INTERMEDIATE', 'Intermediate'),
                    ('EXPERT', 'Expert'),
                ],
                default='INTERMEDIATE',
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='work_environment',
            field=models.CharField(
                choices=[
                    ('INDOOR', 'Indoor'),
                    ('OUTDOOR', 'Outdoor'),
                    ('BOTH', 'Both'),
                ],
                default='INDOOR',
                max_length=10,
            ),
        ),
    ]
