# Generated by Django 6.0 on 2025-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_kyc_ai_verification_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='job_payment_release_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_status_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='kycfiles',
            new_name='kyc_ai_status_idx',
            old_name='kyc_ai_verification_status_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_scope',
            field=models.CharField(choices=[('MINOR_REPAIR', 'Minor Repair (quick fix)'), ('MODERATE_PROJECT', 'Moderate Project (few hours to a day)'), ('MAJOR_RENOVATION', 'Major Renovation (multi-day project)')], default='MINOR_REPAIR', help_text='Scope/complexity of the job', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='skill_level_required',
            field=models.CharField(choices=[('ENTRY', 'Entry Level (basic skills)'), ('INTERMEDIATE', 'Intermediate (experienced)'), ('EXPERT', 'Expert (specialized/licensed)')], default='INTERMEDIATE', help_text='Skill level required for this job', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_environment',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('BOTH', 'Both Indoor & Outdoor')], default='INDOOR', help_text='Where the work will be performed', max_length=10),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='Overall AI confidence (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='ai_details',
            field=models.JSONField(blank=True, default=dict, help_text='Full AI verification details', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='ai_rejection_message',
            field=models.CharField(blank=True, help_text='User-facing rejection message', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='ai_rejection_reason',
            field=models.CharField(blank=True, choices=[('NO_FACE_DETECTED', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces'), ('FACE_TOO_SMALL', 'Face Too Small'), ('MISSING_REQUIRED_TEXT', 'Missing Required Text'), ('IMAGE_TOO_BLURRY', 'Image Too Blurry'), ('RESOLUTION_TOO_LOW', 'Resolution Too Low'), ('INVALID_ORIENTATION', 'Invalid Orientation'), ('UNREADABLE_DOCUMENT', 'Unreadable Document')], help_text='Reason for AI rejection', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='ai_warnings',
            field=models.JSONField(blank=True, default=list, help_text='Warnings from AI', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='face_confidence',
            field=models.FloatField(blank=True, help_text='Face detection confidence (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='face_count',
            field=models.IntegerField(blank=True, help_text='Number of faces detected', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='face_detected',
            field=models.BooleanField(blank=True, help_text='Face detected in document', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text='OCR confidence (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Extracted text via OCR', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Image quality score (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='kycfiles',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When AI verification completed', null=True),
        ),
    ]
