# Generated by Django 6.0 on 2025-12-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_remove_job_job_payment_release_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
