# Generated by Django 6.0 on 2025-12-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_workermaterial_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workermaterial',
            new_name='worker_mate_workerI_082c93_idx',
            old_name='worker_mate_workerI_category_idx',
        ),
        migrations.AlterField(
            model_name='workercertification',
            name='specializationID',
            field=models.ForeignKey(blank=True, help_text='The specific skill this certification is for (e.g., Plumbing, Electrical). Use null for General certifications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.workerspecialization'),
        ),
    ]
