# Generated by Django 6.0 on 2025-12-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_certification_skill_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='soft_skills',
            field=models.TextField(blank=True, default='', help_text="Comma-separated soft skills (e.g., 'Punctual, Team Player, Bilingual')"),
        ),
    ]
