# Generated by Django 6.0 on 2025-12-15 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_add_soft_skills_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workercertification',
            name='specializationID',
            field=models.ForeignKey(help_text='The specific skill this certification is for (e.g., Plumbing, Electrical). All certifications must be linked to a skill.', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.workerspecialization'),
        ),
    ]
