# Generated by Django 6.0 on 2025-12-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_workercertification_specializationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworkerassignment',
            name='client_confirmed_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobworkerassignment',
            name='client_confirmed_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
