# Generated by Django 6.0 on 2026-01-23 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_kyc_extracted_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kycextracteddata',
            new_name='kyc_extract_extract_f12d1b_idx',
            old_name='kyc_extract_extract_status_idx',
        ),
        migrations.RenameIndex(
            model_name='kycextracteddata',
            new_name='kyc_extract_kycID_i_84ba56_idx',
            old_name='kyc_extract_kyc_status_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='adminReferenceNumber',
            field=models.CharField(blank=True, help_text='Reference number from admin when manually processing withdrawal (e.g., bank ref #)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processedByAdmin',
            field=models.ForeignKey(blank=True, help_text='Admin who processed this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='methodType',
            field=models.CharField(choices=[('GCASH', 'GCash'), ('BANK', 'Bank Account'), ('PAYPAL', 'PayPal'), ('VISA', 'Visa/Credit Card'), ('GRABPAY', 'GrabPay'), ('MAYA', 'Maya')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['adminReferenceNumber'], name='accounts_tr_adminRe_720b27_idx'),
        ),
    ]
