# Generated by Django 6.0 on 2026-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_kyc_clearance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email_otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
