# Generated by Django 6.0 on 2026-01-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_email_otp_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycextracteddata',
            name='face_match_completed',
            field=models.BooleanField(default=False, help_text='Whether face matching was completed (True = Azure returned result)'),
        ),
        migrations.AddField(
            model_name='kycextracteddata',
            name='face_match_score',
            field=models.FloatField(blank=True, help_text='Face similarity score between ID and selfie (0-1) from Azure Face API', null=True),
        ),
    ]
