# Generated by Django 6.0.1 on 2026-01-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_kyc_face_match_score'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='accounts_jo_clientI_0890ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='accounts_jo_status_8e7e04_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='accounts_jo_categor_82a59e_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='accounts_jo_urgency_a0aa81_idx',
        ),
    ]
