# Generated by Django 6.0.1 on 2026-02-01 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_wallet_auto_withdraw_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallet',
            new_name='accounts_wa_autoWit_4e6152_idx',
            old_name='accounts_wa_autoWit_idx',
        ),
        migrations.AddField(
            model_name='accounts',
            name='barangay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='barangay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='autoWithdrawEnabled',
            field=models.BooleanField(default=False, help_text='Enable automatic weekly withdrawal requests every Friday'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='lastAutoWithdrawAt',
            field=models.DateTimeField(blank=True, help_text='Last time an auto-withdrawal request was created', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='preferredPaymentMethodID',
            field=models.ForeignKey(blank=True, help_text='Preferred payment method for auto-withdrawals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_withdraw_wallets', to='accounts.userpaymentmethod'),
        ),
    ]
