# Generated by Django 5.2.8 on 2026-02-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_barangay_and_auto_withdraw_fixes'),
    ]

    operations = [
        # Add actionType field to JobLog
        migrations.AddField(
            model_name='joblog',
            name='actionType',
            field=models.CharField(
                choices=[
                    ('STATUS_CHANGE', 'Status Change'),
                    ('JOB_EDITED', 'Job Edited'),
                    ('BUDGET_CHANGED', 'Budget Changed'),
                    ('WORKER_ASSIGNED', 'Worker Assigned'),
                    ('APPLICATION_RECEIVED', 'Application Received'),
                    ('JOB_CREATED', 'Job Created'),
                    ('JOB_DELETED', 'Job Deleted'),
                ],
                default='STATUS_CHANGE',
                help_text='Type of action that triggered this log entry',
                max_length=30,
            ),
        ),
        # Add metadata JSONField to JobLog
        migrations.AddField(
            model_name='joblog',
            name='metadata',
            field=models.JSONField(
                blank=True,
                help_text='Stores additional data like field changes, old/new values, edit reasons',
                null=True,
            ),
        ),
        # Make newStatus nullable (for non-status-change actions)
        migrations.AlterField(
            model_name='joblog',
            name='newStatus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        # Add index for actionType queries
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['actionType', '-createdAt'], name='job_logs_actionT_idx'),
        ),
    ]
