# Generated by Django 5.2.8 on 2026-02-01
# Data migration to populate Specializations minimumRate with DOLE-based rates

from django.db import migrations
from decimal import Decimal


# Philippine blue-collar base pricing by category (in PHP)
# Based on DOLE daily wage rates + market research for Zamboanga region
# Format: (minimum_rate, average_min_project_cost, average_max_project_cost)
PH_DOLE_RATES = {
    'Plumbing': (Decimal('500.00'), Decimal('500.00'), Decimal('5000.00')),
    'Electrical Work': (Decimal('600.00'), Decimal('600.00'), Decimal('8000.00')),
    'Carpentry': (Decimal('800.00'), Decimal('800.00'), Decimal('10000.00')),
    'Cleaning': (Decimal('400.00'), Decimal('400.00'), Decimal('3000.00')),
    'HVAC': (Decimal('1000.00'), Decimal('1000.00'), Decimal('15000.00')),
    'Painting': (Decimal('800.00'), Decimal('800.00'), Decimal('8000.00')),
    'Masonry': (Decimal('1000.00'), Decimal('1000.00'), Decimal('12000.00')),
    'Welding': (Decimal('800.00'), Decimal('800.00'), Decimal('10000.00')),
    'Home Repair': (Decimal('500.00'), Decimal('500.00'), Decimal('5000.00')),
    'Appliance Repair': (Decimal('400.00'), Decimal('400.00'), Decimal('4000.00')),
    'Roofing': (Decimal('1500.00'), Decimal('1500.00'), Decimal('20000.00')),
    'Landscaping': (Decimal('600.00'), Decimal('600.00'), Decimal('6000.00')),
    'Flooring': (Decimal('1200.00'), Decimal('1200.00'), Decimal('15000.00')),
    'Pest Control': (Decimal('800.00'), Decimal('800.00'), Decimal('6000.00')),
    'Moving': (Decimal('500.00'), Decimal('500.00'), Decimal('8000.00')),
    'Demolition': (Decimal('1000.00'), Decimal('1000.00'), Decimal('15000.00')),
    'Pool Service': (Decimal('600.00'), Decimal('600.00'), Decimal('10000.00')),
    'Security Installation': (Decimal('1500.00'), Decimal('1500.00'), Decimal('25000.00')),
    # General/default categories
    'General Labor': (Decimal('400.00'), Decimal('400.00'), Decimal('5000.00')),
    'Handyman': (Decimal('500.00'), Decimal('500.00'), Decimal('5000.00')),
}

# Minimum absolute rate for any category (based on DOLE minimum wage)
DEFAULT_MINIMUM_RATE = Decimal('400.00')
DEFAULT_AVG_MIN = Decimal('400.00')
DEFAULT_AVG_MAX = Decimal('5000.00')


def populate_dole_rates(apps, schema_editor):
    """Populate Specializations with DOLE-based minimum rates"""
    Specializations = apps.get_model('accounts', 'Specializations')
    
    updated_count = 0
    for spec in Specializations.objects.all():
        # Try exact match first
        rates = PH_DOLE_RATES.get(spec.specializationName)
        
        # Try partial match if exact not found
        if not rates:
            for category_name, category_rates in PH_DOLE_RATES.items():
                if category_name.lower() in spec.specializationName.lower():
                    rates = category_rates
                    break
        
        # Use default if no match
        if not rates:
            rates = (DEFAULT_MINIMUM_RATE, DEFAULT_AVG_MIN, DEFAULT_AVG_MAX)
        
        # Only update if minimumRate is 0 (not previously set)
        if spec.minimumRate == Decimal('0.00'):
            spec.minimumRate = rates[0]
            spec.averageProjectCostMin = rates[1]
            spec.averageProjectCostMax = rates[2]
            spec.save()
            updated_count += 1
    
    print(f"✅ Updated {updated_count} specializations with DOLE-based rates")


def reverse_dole_rates(apps, schema_editor):
    """Reverse migration - reset rates to 0"""
    Specializations = apps.get_model('accounts', 'Specializations')
    Specializations.objects.all().update(
        minimumRate=Decimal('0.00'),
        averageProjectCostMin=Decimal('0.00'),
        averageProjectCostMax=Decimal('0.00')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_joblog_action_tracking'),
    ]

    operations = [
        migrations.RunPython(populate_dole_rates, reverse_dole_rates),
    ]
