# Generated by Django 5.2.11 on 2026-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_backjob_team_schedule_confirmations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(choices=[('DISPATCHED', 'Dispatched (on the way)'), ('PENDING', 'Pending confirmation'), ('PRESENT', 'Present (full day)'), ('HALF_DAY', 'Half day'), ('ABSENT', 'Absent'), ('DISPUTED', 'Disputed')], default='PENDING', help_text='Attendance status for this day', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobdispute',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Client-set date for when the backjob will be completed, pending worker/agency confirmation', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationType',
            field=models.CharField(choices=[('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('AGENCY_KYC_APPROVED', 'Agency KYC Approved'), ('AGENCY_KYC_REJECTED', 'Agency KYC Rejected'), ('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_ACCEPTED', 'Application Accepted'), ('APPLICATION_REJECTED', 'Application Rejected'), ('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED_WORKER', 'Job Marked Complete by Worker'), ('JOB_COMPLETED_CLIENT', 'Job Approved by Client'), ('JOB_CANCELLED', 'Job Cancelled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('ESCROW_PAID', 'Escrow Payment Confirmed'), ('REMAINING_PAYMENT_PAID', 'Final Payment Confirmed'), ('PAYMENT_RELEASED', 'Payment Released'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('MESSAGE', 'New Message'), ('REVIEW_RECEIVED', 'Review Received'), ('BACKJOB_REQUESTED', 'Backjob Requested'), ('BACKJOB_APPROVED', 'Backjob Approved'), ('BACKJOB_REJECTED', 'Backjob Rejected'), ('BACKJOB_COMPLETED', 'Backjob Completed'), ('BACKJOB_NEGOTIATION', 'Backjob In Negotiation'), ('BACKJOB_SCHEDULED', 'Backjob Scheduled'), ('CERTIFICATION_APPROVED', 'Certification Approved'), ('CERTIFICATION_REJECTED', 'Certification Rejected'), ('JOB_UPDATED', 'Job Updated'), ('JOB_INVITATION', 'Job Invitation'), ('SYSTEM', 'System')], default='SYSTEM', max_length=50),
        ),
    ]
