# Generated by Django 5.2.11 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_remove_job_job_payment_model_status_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE jobs ADD COLUMN IF NOT EXISTS "workerMarkedOnTheWay" boolean NOT NULL DEFAULT false;',
                    reverse_sql='ALTER TABLE jobs DROP COLUMN IF EXISTS "workerMarkedOnTheWay";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE jobs ADD COLUMN IF NOT EXISTS "workerMarkedOnTheWayAt" timestamp with time zone NULL;',
                    reverse_sql='ALTER TABLE jobs DROP COLUMN IF EXISTS "workerMarkedOnTheWayAt";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE jobs ADD COLUMN IF NOT EXISTS "workerMarkedJobStarted" boolean NOT NULL DEFAULT false;',
                    reverse_sql='ALTER TABLE jobs DROP COLUMN IF EXISTS "workerMarkedJobStarted";'
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE jobs ADD COLUMN IF NOT EXISTS "workerMarkedJobStartedAt" timestamp with time zone NULL;',
                    reverse_sql='ALTER TABLE jobs DROP COLUMN IF EXISTS "workerMarkedJobStartedAt";'
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='job',
                    name='workerMarkedOnTheWay',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='job',
                    name='workerMarkedOnTheWayAt',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='job',
                    name='workerMarkedJobStarted',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='job',
                    name='workerMarkedJobStartedAt',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]
