import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const BRAND_COLOR = '#007AFF';

function formatCurrencyPdf(amount: number): string {
  return `₱${amount.toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatDatePdf(dateString: string): string {
  return new Date(dateString).toLocaleString('en-PH', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

const PDF_STYLES = `
  body { font-family: Arial, sans-serif; padding: 32px; color: #1a1a1a; }
  .header { text-align: center; border-bottom: 3px solid ${BRAND_COLOR}; padding-bottom: 16px; margin-bottom: 24px; }
  .brand { font-size: 28px; font-weight: bold; color: ${BRAND_COLOR}; }
  .receipt-title { font-size: 16px; color: #666; margin-top: 4px; }
  .amount-block { text-align: center; margin: 24px 0; }
  .amount { font-size: 42px; font-weight: bold; color: #1a1a1a; }
  .amount-label { font-size: 14px; color: #666; margin-bottom: 4px; }
  .section-header { font-size: 13px; font-weight: bold; color: ${BRAND_COLOR}; text-transform: uppercase; letter-spacing: 1px; margin: 20px 0 8px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  td { padding: 10px 8px; border-bottom: 1px solid #eee; font-size: 14px; }
  td:first-child { color: #666; width: 45%; }
  td:last-child { font-weight: 600; text-align: right; }
  .total-row td { font-size: 16px; font-weight: bold; border-top: 2px solid #1a1a1a; }
  .party-block { background: #f9f9f9; border-radius: 8px; padding: 12px; margin: 8px 0; }
  .party-name { font-size: 16px; font-weight: bold; }
  .party-label { font-size: 12px; color: #999; }
  .status-completed { color: #16a34a; }
  .status-pending { color: #d97706; }
  .status-failed { color: #dc2626; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; font-size: 11px; color: #999; text-align: center; }
`;

export interface DepositReceiptData {
  transaction_id: string;
  amount: number;
  payment_method: string;
  status: string;
  created_at: string;
  transaction_type_label?: string;
  reference_number?: string | null;
  balance_after?: number | null;
  job?: { id: number; title: string } | null;
}

export async function downloadDepositReceiptPdf(transaction: DepositReceiptData): Promise<void> {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <style>${PDF_STYLES}</style>
    </head>
    <body>
      <div class="header">
        <div class="brand">iAyos</div>
        <div class="receipt-title">${transaction.transaction_type_label || 'Transaction Receipt'}</div>
      </div>
      <div class="amount-block">
        <div class="amount-label">Amount</div>
        <div class="amount">${formatCurrencyPdf(transaction.amount)}</div>
      </div>
      <div class="section-header">Transaction Details</div>
      <table>
        <tr><td>Transaction ID</td><td>${transaction.transaction_id}</td></tr>
        ${transaction.reference_number ? `<tr><td>Reference No.</td><td>${transaction.reference_number}</td></tr>` : ''}
        <tr><td>Payment Method</td><td>${transaction.payment_method.toUpperCase()}</td></tr>
        <tr><td>Status</td><td class="status-${transaction.status.toLowerCase()}">${transaction.status.toUpperCase()}</td></tr>
        <tr><td>Date &amp; Time</td><td>${formatDatePdf(transaction.created_at)}</td></tr>
        ${transaction.balance_after != null ? `<tr><td>Balance After</td><td>${formatCurrencyPdf(transaction.balance_after)}</td></tr>` : ''}
        ${transaction.job ? `<tr><td>Related Job</td><td>${transaction.job.title}</td></tr>` : ''}
      </table>
      <div class="footer">
        This receipt was generated by iAyos. For inquiries, contact support@iayos.com.<br/>
        iAyos acts as an escrow intermediary. This does not constitute an official BIR receipt.
      </div>
    </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Save Receipt',
    UTI: 'com.adobe.pdf',
  });
}

export interface JobReceiptData {
  transaction_id?: string;
  completed_at?: string | null;
  job?: {
    id: number;
    title: string;
    job_type?: string;
    status?: string;
  } | null;
  payments?: {
    job_budget?: number;
    platform_fee?: number;
    total_paid?: number;
    worker_earnings?: number;
    escrow_amount?: number;
    remaining_payment?: number;
  } | null;
  client?: {
    name: string;
    email?: string;
  } | null;
  worker?: {
    name: string;
    email?: string;
  } | null;
}

export async function downloadJobReceiptPdf(
  receipt: JobReceiptData,
  userRole: 'CLIENT' | 'WORKER'
): Promise<void> {
  const isClient = userRole === 'CLIENT';
  const payments = receipt.payments || {};

  const paymentRows = isClient
    ? `
        <tr><td>Job Budget</td><td>${formatCurrencyPdf(payments.job_budget || 0)}</td></tr>
        ${payments.escrow_amount != null ? `<tr><td>Escrow (50%)</td><td>${formatCurrencyPdf(payments.escrow_amount)}</td></tr>` : ''}
        ${payments.remaining_payment != null ? `<tr><td>Remaining (50%)</td><td>${formatCurrencyPdf(payments.remaining_payment)}</td></tr>` : ''}
        <tr><td>Platform Fee</td><td>${formatCurrencyPdf(payments.platform_fee || 0)}</td></tr>
        <tr class="total-row"><td>Total Paid</td><td>${formatCurrencyPdf(payments.total_paid || 0)}</td></tr>
      `
    : `
        <tr><td>Job Budget</td><td>${formatCurrencyPdf(payments.job_budget || 0)}</td></tr>
        <tr><td>Platform Fee</td><td>-${formatCurrencyPdf(payments.platform_fee || 0)}</td></tr>
        <tr class="total-row"><td>Your Earnings</td><td>${formatCurrencyPdf(payments.worker_earnings || 0)}</td></tr>
      `;

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <style>
        ${PDF_STYLES}
        .job-title-block { text-align: center; margin: 16px 0 24px; }
        .job-title-text { font-size: 20px; font-weight: bold; }
        .job-id { font-size: 13px; color: #999; margin-top: 4px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="brand">iAyos</div>
        <div class="receipt-title">Job Completion Receipt</div>
      </div>

      <div class="job-title-block">
        <div class="job-title-text">${receipt.job?.title || 'Job Receipt'}</div>
        ${receipt.job?.id ? `<div class="job-id">Job #${receipt.job.id}</div>` : ''}
      </div>

      <div class="section-header">Job Details</div>
      <table>
        ${receipt.job?.job_type ? `<tr><td>Type</td><td>${receipt.job.job_type}</td></tr>` : ''}
        ${receipt.job?.status ? `<tr><td>Status</td><td>${receipt.job.status}</td></tr>` : ''}
        ${receipt.completed_at ? `<tr><td>Completed</td><td>${formatDatePdf(receipt.completed_at)}</td></tr>` : ''}
        ${receipt.transaction_id ? `<tr><td>Transaction ID</td><td>${receipt.transaction_id}</td></tr>` : ''}
      </table>

      <div class="section-header">Payment Summary</div>
      <table>${paymentRows}</table>

      ${receipt.client ? `
        <div class="section-header">Client</div>
        <div class="party-block">
          <div class="party-name">${receipt.client.name}</div>
          ${receipt.client.email ? `<div class="party-label">${receipt.client.email}</div>` : ''}
        </div>
      ` : ''}

      ${receipt.worker ? `
        <div class="section-header">Worker</div>
        <div class="party-block">
          <div class="party-name">${receipt.worker.name}</div>
          ${receipt.worker.email ? `<div class="party-label">${receipt.worker.email}</div>` : ''}
        </div>
      ` : ''}

      <div class="footer">
        This receipt was generated by iAyos. For inquiries, contact support@iayos.com.<br/>
        iAyos acts as an escrow intermediary. This does not constitute an official BIR receipt.
      </div>
    </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Save Receipt',
    UTI: 'com.adobe.pdf',
  });
}
