"""
Django settings for iayos_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import datetime
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load .env from backend root (one directory above src)
load_dotenv(BASE_DIR.parent / ".env")


load_dotenv(BASE_DIR.parent / ".env.local", override=True)

# ============================================================================
# SENTRY INITIALIZATION (Early - before other imports)
# ============================================================================
try:
    from iayos_project.observability import configure_sentry
    configure_sentry()
except ImportError:
    pass  # Observability module not yet loaded

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, DJANGO_SECRET_KEY must be set in environment variables
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('ENVIRONMENT', 'development') == 'production':
        raise ValueError("DJANGO_SECRET_KEY must be set in production environment")
    # Only use insecure default in development
    SECRET_KEY = 'django-insecure-dev-only-change-in-production'
    print("⚠ Using insecure SECRET_KEY - set DJANGO_SECRET_KEY in production!")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False for safety - must explicitly enable in development
DEBUG = os.environ.get('DEBUG', 'false').lower() == 'true'

# SECURITY: In production, ALLOWED_HOSTS must be explicitly set
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
if not any(ALLOWED_HOSTS) or ALLOWED_HOSTS == ['']:
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']
    else:
        print("⚠ ALLOWED_HOSTS not set - defaulting to localhost only")
        ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for Django Channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'channels',
    'ninja_extra',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    #internal
    'accounts',
    'agency',
    'adminpanel',
    'jobs',
    'profiles',
    'ml',  # Machine Learning - Job Completion Time Prediction

]

MIDDLEWARE = [
    'iayos_project.observability.RequestIDMiddleware',  # Request ID for tracing (first)
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'iayos_project.rate_limiting.RateLimitMiddleware',  # Rate limiting (last)
]

# ============================================================================
# OBSERVABILITY CONFIGURATION
# ============================================================================

# Sentry Error Tracking (Optional - set in environment)
SENTRY_DSN = os.environ.get('SENTRY_DSN', None)
SENTRY_TRACES_SAMPLE_RATE = float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1'))
SENTRY_PROFILES_SAMPLE_RATE = float(os.environ.get('SENTRY_PROFILES_SAMPLE_RATE', '0.1'))
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')
APP_VERSION = os.environ.get('APP_VERSION', '1.0.0')

# Logging configuration
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')
JSON_LOGGING = os.environ.get('JSON_LOGGING', 'false').lower() == 'true'

# Rate limiting
RATE_LIMIT_DISABLED = os.environ.get('RATE_LIMIT_DISABLED', 'false').lower() == 'true'

# Query caching
QUERY_CACHE_DISABLED = os.environ.get('QUERY_CACHE_DISABLED', 'false').lower() == 'true'

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': os.getenv('AUTH_GOOGLE_ID'),
            'secret': os.getenv('AUTH_GOOGLE_SECRET'),
        }
    }
}

# CORS Settings - Allow frontend during dev
# settings.py
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins in development (restrict in production)

# Legacy CORS settings (kept for reference)
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://localhost:8000",
#     "http://127.0.0.1:8000",
# ]

# Get the frontend URL from environment for CSRF trust
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3400')
API_URL = os.getenv('EXPO_PUBLIC_API_URL', 'http://localhost:8000').strip('"')

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3400",
    "http://127.0.0.1:3400",
    "http://localhost:3500",
    "http://127.0.0.1:3500",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://10.0.2.2:8000",  # Android emulator host access
    "http://192.168.254.116:3500",  # IP address for LAN access (port 3500)
    "http://192.168.254.116:8000",  # Backend IP for LAN access
    FRONTEND_URL,  # Dynamic frontend URL from env
    API_URL,  # Dynamic API URL from env
]

# Allow credentials (cookies) to be sent
CORS_ALLOW_CREDENTIALS = True

# Allow common headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding", 
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Allow common methods
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET", 
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# CSRF Settings - Exempt API endpoints since we're using JWT
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

ROOT_URLCONF = 'iayos_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iayos_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Toggle between local PostgreSQL and Neon cloud database
USE_LOCAL_DB = os.getenv("USE_LOCAL_DB", "false").lower() == "true"

# Connection pooling settings
DB_CONN_MAX_AGE = int(os.getenv("DB_CONN_MAX_AGE", "60"))  # Persistent connections for 60 seconds
DB_CONN_HEALTH_CHECKS = os.getenv("DB_CONN_HEALTH_CHECKS", "true").lower() == "true"

if USE_LOCAL_DB:
    # Local PostgreSQL - no SSL required, with connection pooling
    DATABASES = {
        'default': dj_database_url.parse(
            os.getenv("DATABASE_URL_LOCAL", "postgresql://iayos_user:iayos_local_pass@postgres:5432/iayos_db"),
            conn_max_age=DB_CONN_MAX_AGE,
            conn_health_checks=DB_CONN_HEALTH_CHECKS,
            ssl_require=False,
        )
    }
else:
    # Neon Cloud PostgreSQL - SSL required, with connection pooling
    DATABASES = {
        'default': dj_database_url.parse(
            os.getenv("DATABASE_URL"),
            conn_max_age=DB_CONN_MAX_AGE,
            conn_health_checks=DB_CONN_HEALTH_CHECKS,
            ssl_require=True,
        )
    }

from datetime import timedelta

AUTH_USER_MODEL = "accounts.Accounts"

# JWT Settings for custom PyJWT implementation
JWT_ACCESS_TOKEN_LIFETIME = timedelta(minutes=60)  # 1 hour
JWT_REFRESH_TOKEN_LIFETIME = timedelta(days=7)     # 7 days

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
# Used when USE_LOCAL_DB=true for offline/defense mode
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cookie settings for cross-origin localhost development
SESSION_COOKIE_SECURE = False  # For development (must be False for http://localhost)
CSRF_COOKIE_SECURE = False     # For development (must be False for http://localhost)
SESSION_COOKIE_SAMESITE = None  # Allow cross-origin cookies on localhost
CSRF_COOKIE_SAMESITE = None     # Allow cross-origin cookies on localhost
SESSION_COOKIE_DOMAIN = None    # Use default domain
CSRF_COOKIE_HTTPONLY = False    # Allow JavaScript to read CSRF token


RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
RESEND_BASE_URL = "https://api.resend.com"

SOCIALACCOUNT_LOGIN_ON_GET = True

# Import custom Supabase adapter for new secret API keys
from iayos_project.supabase_adapter import create_supabase_client

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY", "")
# New secret API key format (sb_secret_...) - replaces the old service_role JWT
SUPABASE_SECRET_KEY = os.getenv("SUPABASE_SECRET_KEY") or os.getenv("SUPABASE_SERVICE_KEY", "")

# Create Supabase client using new secret API keys
SUPABASE = None
if SUPABASE_URL and SUPABASE_SECRET_KEY:
    try:
        # Use custom adapter that works with new secret API keys
        SUPABASE = create_supabase_client(
            url=SUPABASE_URL,
            secret_key=SUPABASE_SECRET_KEY,
            anon_key=SUPABASE_ANON_KEY
        )
        print("✓ Supabase client initialized successfully with secret API key")
    except Exception as e:
        print(f"✗ Failed to initialize Supabase client: {e}")
        print("File storage features will be disabled.")
elif SUPABASE_URL and SUPABASE_ANON_KEY:
    try:
        # Fallback: use anon key only (limited access)
        SUPABASE = create_supabase_client(
            url=SUPABASE_URL,
            secret_key=SUPABASE_ANON_KEY,
            anon_key=SUPABASE_ANON_KEY
        )
        print("⚠ Supabase initialized with ANON key only (RLS restrictions apply)")
    except Exception as e:
        print(f"✗ Failed to initialize Supabase client: {e}")
else:
    print("✗ SUPABASE_URL or SUPABASE_SECRET_KEY not set. File storage features will be disabled.")

# =====================================================
# UNIFIED STORAGE ADAPTER
# =====================================================
# When USE_LOCAL_DB=true, use local file storage instead of Supabase
# This enables fully offline operation for defense demos

USE_LOCAL_STORAGE = os.getenv('USE_LOCAL_DB', 'false').lower() == 'true'

if USE_LOCAL_STORAGE:
    from iayos_project.local_storage import create_local_storage_client
    
    # Get the backend URL for serving media files
    # In defense mode, this should be the laptop's hotspot IP
    BACKEND_URL = os.getenv('EXPO_PUBLIC_API_URL', 'http://localhost:8000')
    
    STORAGE = create_local_storage_client(
        media_root=str(MEDIA_ROOT),
        media_url=MEDIA_URL,
        base_url=BACKEND_URL
    )
    print(f"✓ Local file storage enabled (offline mode)")
    print(f"  Media root: {MEDIA_ROOT}")
    print(f"  Media URL: {BACKEND_URL}{MEDIA_URL}")
else:
    # Use Supabase for cloud storage
    STORAGE = SUPABASE
    if STORAGE:
        print("✓ Using Supabase for file storage (cloud mode)")
    else:
        print("⚠ No file storage configured - uploads will fail")

# Xendit Configuration (Legacy - for rollback)
XENDIT_API_KEY = os.getenv("XENDIT_API_KEY")  # Must be set in .env.docker
XENDIT_WEBHOOK_TOKEN = os.getenv("XENDIT_WEBHOOK_TOKEN", "")  # Optional: for webhook verification
XENDIT_TEST_MODE = True  # Always True for development
XENDIT_TEST_ACCOUNT_NAME = os.getenv("XENDIT_TEST_ACCOUNT_NAME", "Test GCash User")
XENDIT_TEST_ACCOUNT_NUMBER = os.getenv("XENDIT_TEST_ACCOUNT_NUMBER", "09123456789")

# =====================================================
# PAYMONGO PAYMENT GATEWAY (Primary)
# =====================================================
# PayMongo API keys - Get from https://dashboard.paymongo.com/developers
# Test keys: sk_test_ / pk_test_ | Live keys: sk_live_ / pk_live_
PAYMONGO_SECRET_KEY = os.getenv("PAYMONGO_SECRET_KEY", "")
PAYMONGO_PUBLIC_KEY = os.getenv("PAYMONGO_PUBLIC_KEY", "")
PAYMONGO_WEBHOOK_SECRET = os.getenv("PAYMONGO_WEBHOOK_SECRET", "")

# Admin email for withdrawal notifications (manual processing alerts)
ADMIN_WITHDRAWAL_EMAIL = os.getenv("ADMIN_WITHDRAWAL_EMAIL", "")

# Payment provider selection: "paymongo" (default) or "xendit" (legacy rollback)
PAYMENT_PROVIDER = os.getenv("PAYMENT_PROVIDER", "paymongo")

# Frontend URL for redirects
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# Ngrok URL for development webhook testing (set this when using ngrok)
# Example: NGROK_URL=https://abcd1234.ngrok-free.app
NGROK_URL = os.getenv("NGROK_URL", None)

# Backend URL (used for payment redirects in production)
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

# Django Channels Configuration
ASGI_APPLICATION = "iayos_project.asgi.application"

# Redis URL for Channel Layer and Caching
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")

# Channel Layers - Use Redis for production (supports multiple workers/replicas)
# Falls back to InMemoryChannelLayer only if Redis is not configured
if REDIS_URL and REDIS_URL != "none":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
                "capacity": 1500,  # Maximum messages per channel
                "expiry": 60,  # Message expiry in seconds
            },
        },
    }
    print(f"✓ Using Redis Channel Layer: {REDIS_URL.split('@')[-1] if '@' in REDIS_URL else REDIS_URL}")
else:
    # Fallback for local development without Redis
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        },
    }
    print("⚠ Using InMemoryChannelLayer - WebSockets won't work across multiple workers")

# Django Cache Configuration - Use Redis
if REDIS_URL and REDIS_URL != "none":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "iayos",
            "TIMEOUT": 300,  # 5 minutes default cache timeout
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Frontend URL for redirects
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")