"""
Django settings for iayos_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import datetime
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load .env from backend root (one directory above src)
load_dotenv(BASE_DIR.parent / ".env")


load_dotenv(BASE_DIR.parent / ".env.local", override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-ss_o*cm)=s&gj!mnt)w&6+-20*s+4imz84l1=m_(59s0ztn9y+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts in development (restrict in production)


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for Django Channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'channels',
    'ninja_extra',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    #internal
    'accounts',
    'agency',
    'adminpanel',
    'jobs',
    'profiles'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': os.getenv('AUTH_GOOGLE_ID'),
            'secret': os.getenv('AUTH_GOOGLE_SECRET'),
        }
    }
}

# CORS Settings - Allow frontend during dev
# settings.py
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins in development (restrict in production)

# Legacy CORS settings (kept for reference)
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://localhost:8000",
#     "http://127.0.0.1:8000",
# ]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://10.0.2.2:8000",  # Android emulator host access
]

# Allow credentials (cookies) to be sent
CORS_ALLOW_CREDENTIALS = True

# Allow common headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding", 
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Allow common methods
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET", 
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# CSRF Settings - Exempt API endpoints since we're using JWT
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

ROOT_URLCONF = 'iayos_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iayos_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        os.getenv("DATABASE_URL"),
        conn_max_age=0,
        ssl_require=True,
    )
}

from datetime import timedelta

AUTH_USER_MODEL = "accounts.Accounts"

# JWT Settings for custom PyJWT implementation
JWT_ACCESS_TOKEN_LIFETIME = timedelta(minutes=60)  # 1 hour
JWT_REFRESH_TOKEN_LIFETIME = timedelta(days=7)     # 7 days

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Add these to your settings.py
SESSION_COOKIE_SECURE = False  # For development
CSRF_COOKIE_SECURE = False     # For development
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'


RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
RESEND_BASE_URL = "https://api.resend.com"

SOCIALACCOUNT_LOGIN_ON_GET = True

# Import custom Supabase adapter for new secret API keys
from iayos_project.supabase_adapter import create_supabase_client

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY", "")
# New secret API key format (sb_secret_...) - replaces the old service_role JWT
SUPABASE_SECRET_KEY = os.getenv("SUPABASE_SECRET_KEY") or os.getenv("SUPABASE_SERVICE_KEY", "")

# Create Supabase client using new secret API keys
SUPABASE = None
if SUPABASE_URL and SUPABASE_SECRET_KEY:
    try:
        # Use custom adapter that works with new secret API keys
        SUPABASE = create_supabase_client(
            url=SUPABASE_URL,
            secret_key=SUPABASE_SECRET_KEY,
            anon_key=SUPABASE_ANON_KEY
        )
        print("✓ Supabase client initialized successfully with secret API key")
    except Exception as e:
        print(f"✗ Failed to initialize Supabase client: {e}")
        print("File storage features will be disabled.")
elif SUPABASE_URL and SUPABASE_ANON_KEY:
    try:
        # Fallback: use anon key only (limited access)
        SUPABASE = create_supabase_client(
            url=SUPABASE_URL,
            secret_key=SUPABASE_ANON_KEY,
            anon_key=SUPABASE_ANON_KEY
        )
        print("⚠ Supabase initialized with ANON key only (RLS restrictions apply)")
    except Exception as e:
        print(f"✗ Failed to initialize Supabase client: {e}")
else:
    print("✗ SUPABASE_URL or SUPABASE_SECRET_KEY not set. File storage features will be disabled.")

# Xendit Configuration
XENDIT_API_KEY = os.getenv("XENDIT_API_KEY")  # Must be set in .env.docker
XENDIT_WEBHOOK_TOKEN = os.getenv("XENDIT_WEBHOOK_TOKEN", "")  # Optional: for webhook verification
XENDIT_TEST_MODE = True  # Always True for development
XENDIT_TEST_ACCOUNT_NAME = os.getenv("XENDIT_TEST_ACCOUNT_NAME", "Test GCash User")
XENDIT_TEST_ACCOUNT_NUMBER = os.getenv("XENDIT_TEST_ACCOUNT_NUMBER", "09123456789")

# Frontend URL for redirects
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# Django Channels Configuration
ASGI_APPLICATION = "iayos_project.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}

# Frontend URL for redirects
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")